using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.SessionState;

namespace BTL_LTW_G15
{
    public class Global : System.Web.HttpApplication
    {
        public const string USERNAME = "usname";
        public const string PASSWORD = "uspass";
        public const string USERLIST = "USLIST";
        public const string DANHSACHTINTUC = "DSTT";
        public const string DANHSACHCTTT = "DSCTTT";
        public const string DANHSACHGOPY = "DSGY";
        public const string DANHSACHCHUONGTRINH = "DSCT";
        public const string State = "state";
        public const string PeopleCount = "a";
        public const string PC = "a";
        public const string List = "b";
        protected void Application_Start(object sender, EventArgs e)
        {
            Application[DANHSACHTINTUC] = createDSTT();
            Application[DANHSACHCTTT] = createDSCTTT();
            Application[USERLIST] = createUList();
            Application[DANHSACHGOPY] = createDSGYList();
            Application[DANHSACHCHUONGTRINH] = createDSCTList();
            Application[PeopleCount] = createPCList();
            Application[PC] = createDemList();
            Application[List] = createnewList();
        }

        private List<Nguoixem> createnewList()
        {
            return new List<Nguoixem>() { };
        }

        private List<string> createDemList()
        {
            return new List<string>() { };
        }

        private List<string> createPCList()
        {
            return new List<string>()
            {
            };
        }

        private List<Chuongtrinh> createDSCTList()
        {
            return new List<Chuongtrinh>
            {
                new Chuongtrinh(){ID = 1,MST="1", BannerUrl ="resource/images/banner-ct1.jpg",Title="Chương trình học bổng phát triển trẻ em",Content="Giáo dục có thể giúp trẻ em nghèo phát triển khả năng và có khởi đầu công bằng hơn. Tuy nhiên, vẫn còn nhiều trẻ em Việt Nam có ít cơ hội học tập và có nguy cơ bỏ học do nghèo đói và khó khăn cũng như các vấn đề về sức khỏe, địa lý, rào cản kiến thức và khuyết tật..<br/> <br/> Nhờ sự hỗ trợ nhiệt tình của các nhà tài trợ, mỗi năm Chương trình Hỗ trợ Học bổng của saigonchildren trao gần 2.000 học bổng cho trẻ em và thanh thiếu niên thiệt thòi, để các em có thể tiếp tục việc học và phát triển trọn vẹn tiềm năng của mình. Số lượng trẻ trải dài từ cấp tiểu học cho đến bậc đại học. <br/> </br> Chúng tôi áp dụng phương pháp tiếp cận toàn diện để giúp trẻ em và thanh thiếu niên tiếp tục theo học tại trường thông qua một hệ thống gọi là Mạng Lưới Cộng Đồng Hỗ Trợ Phát Triển Trẻ Em. Mạng lưới này sẽ liên kết giáo viên, đại diện địa phương và các bạn trẻ ở cấp địa phương. Qua đó, các thành viên cùng đánh giá nhu cầu của từng trẻ, theo dõi sự tiến bộ của các em cũng như cung cấp cho các em những hỗ trợ liên quan để tiếp cận giáo dục.",ImageUrl="resource/images/project1.png"},
                new Chuongtrinh(){ID = 2,MST="1", BannerUrl ="resource/images/banner-ct2.jpg",Title="Chương trình xây dựng trường học",Content="Mang lại cơ sở vật chất giáo dục phù hợp và tạo điều kiện học tập đầy đủ cho trẻ em có hoàn cảnh thiệt thòi là mối quan tâm của saigonchildren ngay từ những ngày đầu mới thành lập. Chương trình Xây dựng Trường Học và Môi trường Học đường sử dụng các khoảng tài trợ từ phía tư nhân, cùng với những đóng góp từ chính quyền, để xây dựng trường học được sở hữu và vận hành bởi địa phương.<br/> <br/> Ngoài việc đảm bảo sự vững chắc, an toàn và tính thẩm mĩ cho trường, saigonchildren còn xây dựng thêm cơ sở vệ sinh, thư viện, sân chơi và phòng học đặc biệt tùy theo nhu cầu của mỗi địa phương.<br/> <br/> Saigonchildren tận dụng những trường học này cùng với mạng lưới cộng đồng vững chắc để để nâng cao ý thức địa phương về những vấn đề như tính bền cững, bảo vệ môi trường, sức khỏe…<br/> <br/>Từ ngôi trường đầu tiên tại huyện Cần Giờ năm 1993, saigonchildren đã xây dựng hơn 503 phòng học, mở ra tương lai tươi sáng cho hơn 1500 trẻ em có hoàn cảnh thiệt thòi mỗi năm, từ Trà Vinh ở khu vực phía Nam trải dài đến Tuyên Quang ở khu vực miền Bắc.",ImageUrl="resource/images/project2.jpg"},
                new Chuongtrinh(){ID = 3,MST="1", BannerUrl ="resource/images/banner-ct3.jpg",Title="Chương trình đào tạo nghề và kĩ năng",Content="Saigonchildren dùng giáo dục làm phương cách để hỗ trợ trẻ em có hoàn cảnh khó khăn thoát nghèo. Khẳng định tầm quan trọng của giáo dục nghề nghiệp cho trẻ em và thanh thiếu niên có hoàn cảnh khó khăn, Chương Trình Đào Tạo Nghề và Kĩ Năng đã ra đời trên tinh thần đó.<br/> <br/>Qua 25 năm, hơn 2.264.000 USD đã được saigonchildren đầu tư cùng với sự hỗ trợ chuyên môn để hơn 10.000 lượt trẻ em và thanh thiếu niên có hoàn cảnh khó khăn có cơ hội học nghề ngắn hạn, học tiếng Anh, vi tính, kỹ năng sống tại Trường Dạy Tiếng Anh và Dạy nghề Thăng Long để sẵn sàng làm việc hiệu quả.<br/> <br/>Ngoài ra, cơ hội tham gia các hoạt động vui chơi giải trí và các hoạt động xã hội cũng là một phần không thể thiếu của các em trong chương trình này. Góp phần đào tạo trẻ em và thanh thiếu niên thiệt thòi thành những cá nhân tự tin, tự lập, có tay nghề và có trách nhiệm là mục tiêu mà saigonchildren cùng đối tác địa phương đã, đang và sẽ luôn tiếp tục hướng đến.", ImageUrl = "resource/images/project3.jpg"},
                new Chuongtrinh(){ID = 4,MST="1", BannerUrl ="resource/images/banner-ct4.jpg",Title="Chương trình giáo dục đặc biệt",Content="Saigonchildren hỗ trợ trẻ em khuyết tật bằng việc thực hiện các dự án nhằm giúp các em có cuộc sống tốt hơn thông qua việc tiếp cận giáo dục thích hợp và các chương trình đào tạo thuộc chương trình “Giáo dục đặc biệt” (SNEP).<br/> <br/>Saigonchildren còn hợp tác với các tổ chức chuyên môn khắp Việt nam để hỗ trợ các trẻ có những khuyết tật như bại não, khiếm thị, khiếm thính và các khuyết tật khác. Saigonchildren cung cấp các khóa huấn luyện cho các tổ chức địa phương nhằm nhằm nâng cao năng lực của các nhà chuyên môn làm việc với trẻ em khuyết tật. Thông qua các dự án này, nhiều ý tưởng mới, phương cách giáo dục phù hợp được thực hiện, nhiều mô hình giáo dục hiệu quả được nhân rộng, mạng lưới các nhà chuyên môn được kết nối và học hỏi lẫn nhau.<br/> <br/> Saigonchildren tập trung vào mảng giáo dục cho trẻ tự kỉ, bao gồm phát hiện sớm dựa vào cộng đồng, và can thiệp sớm theo mô hình giáo dục đa ngành với sự tham gia của các nhà âm ngữ trị liệu, hoạt động trị liệu, nhà giáo dục và phụ huynh. Điều này được thực hiện thông qua việc kết hợp với rất nhiều tổ chức chuyên môn trong và ngoài nước nhằm phát triển các nguồn tài liệu và các phương pháp trị liệu có bằng chứng khoa học có thể ứng dụng trong bối cảnh Việt Nam, hướng tới việc hình thành một Trung tâm Nguồn và xây dựng một mạng lưới quốc gia về chăm sóc giáo dục trẻ em tự kỷ có chất lượng cao.", ImageUrl = "resource/images/project4.jpg"},
                new Chuongtrinh(){ID = 5,MST ="1", BannerUrl="resource/images/banner-news2.jpg",Title="Trung thu đủ đầy, niềm vui trọn vẹn cho trẻ em Đồng Nai",Content="Giữa mùa hè oi ả, 24 bé nhỏ đang tham gia lớp Can thiệp sớm miễn phí của saigonchildren dành cho trẻ tự kỷ có hoàn cảnh khó khăn, cùng với người chăm sóc và các anh chị em thân thiết, đã cùng nhau hòa mình vào thiên nhiên trong chuyến đi dã ngoại vào cuối tuần qua. <br/> <br/> Năm nay, đồng hành cùng trẻ trong chuyến tham quan còn có các cô chú tình nguyện viên đến từ công ty Intel Việt Nam. Đến với nông trại, các “nông dân nhí” vô cùng phấn khởi khi lần đầu nhìn thấy và chạm vào các loài thú thân thiện được nuôi tại đây. Các bé cũng không ngại chơi với bùn đất, bắt cá bắt ốc, đến thăm vườn rau xanh mát, hay xới đất trồng cây trong những chiếc chậu nhỏ xinh. Các bé sớm trở nên khắng khít và cởi mở với các cô chú sau khi cùng trải qua các trò chơi thú vị trong cả buổi sáng hôm ấy. <br/> <br/> Gác lại giờ nghỉ trưa để nạp năng lượng, các em đều háo hức bước vào hoạt động tô tượng, nặn đất sét, và tự tay gói bánh ít để rèn luyện sự khéo léo và tính kiên nhẫn. Cuối ngày, hàng loạt tiết mục văn nghệ góp vui bởi các bé cũng được trình diễn một cách ngẫu hứng và tràn ngập tiếng cười dưới sự cổ vũ nhiệt tình từ các cô chú tài trợ. Phụ huynh bé M. chia sẻ, “Mọi năm, rất ít có cơ hội cho bé đi chơi ngoài trời với đông bạn bè như thế, và cũng như được gặp nhiều loài động vật đến vậy. Nhìn bé chơi vui thế này thì chị cũng mừng và vui lây.” <br/> <br/> Vận động ngoài trời không chỉ quan trọng với sự phát triển toàn diện của trẻ tự kỷ mà nó còn thật đáng quý, bởi lẽ vì những khó khăn về giao tiếp và hành vi, hiếm khi có dịp các em được thỏa thích nô đùa ở một không gian mới mẻ bên ngoài gia đình hay trường lớp. Trẻ em, dù là ai, cũng đều xứng đáng có được những trải nghiệm thích hợp và kỷ niệm tuổi thơ đáng nhớ.",ImageUrl="resource/images/news2.png"},
                new Chuongtrinh(){ID=6,MST="1",BannerUrl = "resource/images/banner-news11.png", Title = "Ngày hội dinh dưỡng cùng trẻ em Tiểu học Trà Vinh", ImageUrl = "resource/images/news11.jpg",Content = "Vào ngày 23 tháng Tư 2023, tại trường Tiểu học Hiếu Trung B (huyện Tiểu Cần, tỉnh Trà Vinh) đã diễn ra ngày hội dinh dưỡng với chủ đề “Bữa ăn Thông thái – Ươm mầm Tương lai” dành cho 405 em đang học tập tại ngôi trường này. Đây là sự kiện nằm trong hợp phần dinh dưỡng cho hơn 1.000 trẻ em có hoàn cảnh khó khăn tại tỉnh Trà Vinh, thuộc dự án “Cùng nhau hành động – Hỗ trợ nỗ lực phục hồi hậu COVID-19” mà Saigon Children’s Charity thực hiện với sự hỗ trợ của Prudential Việt Nam tại hai tỉnh Trà Vinh và Bình Thuận. <br/> <br/> Vào hôm ấy, các em đã được tìm hiểu về tháp dinh dưỡng cũng như giá trị dinh dưỡng của các món ăn thông qua trò chơi “Chiếc hộp bí mật”. Không những thế, các em còn được hướng dẫn về cách “tô màu cho bữa ăn” để học về đa dạng chất dinh dưỡng thông qua màu sắc các món trong bữa ăn, cũng như quy tắc phân bổ để có một bữa ăn cân bằng các nhóm chất. Sự kiện còn có sự tham gia của hơn 100 phụ huynh trong hoạt động hội thảo cùng chuyên gia, qua đó phụ huynh được chia sẻ các quy tắc cơ bản để xây dựng bữa ăn lành mạnh, dinh dưỡng cho trẻ. <br/> <br/> Trong suốt 55 ngày, từ tháng Ba cho đến hết năm học 2022 – 2023, 64.900 bữa phụ đã được hỗ trợ cho 1.180 học sinh mẫu giáo và tiểu học tại huyện Tiểu Cần, bao gồm thực hiện tại 4 trường, trong đó có hai trường mẫu giáo (Hiếu Tử, Hùng Hoà) và hai trường tiểu học (Hiếu Tử C, Hiếu Trung B). Vào mỗi buổi sáng, những chuyến xe chở đầy thức ăn sẽ đáp tại sân trường, các thầy cô phụ trách nhận nhiệm vụ phân loại và sắp xếp ngay ngắn để đảm bảo có đủ khẩu phần theo từng lớp học, từng loại chay và mặn khác nhau. Những lớp nhỏ sẽ được thầy cô đưa suất ăn đến tận lớp học; trong khi các em lớn hơn sẽ cử đại diện đến nơi tập trung và mang chúng về lớp cho các bạn vào lúc 9g sáng."},
                new Chuongtrinh(){ID=7,MST = "1", BannerUrl = "resource/images/banner-news7.png", Title = "2 ngày 1 đêm tràn ngập thanh âm tuổi trẻ của các bạn học sinh",ImageUrl = "resource/images/news7.png",Content="Cuối tháng 7 này, Trại hè Sinh viên 2023 vừa được diễn ra tại Đồng Nai dành cho sinh viên đang và đã nằm trong chương trình học bổng của saigonchildren ở cấp bậc đại học. Như mọi năm, Trại hè như một hoạt động ngoại khóa để các bạn có cơ hội tham gia vui chơi, hình thành các kỹ năng và mối quan hệ bạn bè mới; cũng như để gạt đi nỗi âu lo trong cuộc sống và tìm thấy nơi thể hiện sự nhiệt huyết tuổi trẻ vốn có của mình. <br/> <br/> Chủ đề trại năm nay mang tên “Happy Bridges” – trở thành chiếc cầu nối giữa các cá nhân xa lạ lại gần nhau hơn. Vì thế trong lần tổ chức này, các trại sinh đã cùng lăn xả hết mình với những thử thách được đề ra, với mục đích phát huy tinh thần đoàn kết đồng đội và văn hóa tập thể.<br/> <br/> Cuộc chơi khởi động bằng hoạt động dựng và trang trí lều trại bằng bóng bay, sáng tạo bảng tên nhóm thật phong cách và trình bày ý nghĩa của chúng trước Ban giám khảo để nhận các số điểm đầu tiên. Sự háo hức được tiếp tục khi tiến tới Lễ khai mạc và tiến hành các nghi thức đặc trưng, bao gồm vẽ mặt màu và nhảy theo bài hát chủ đề trại."},
                new Chuongtrinh(){ID=8,MST = "1", BannerUrl = "resource/images/banner-news8.png", Title = "Tham gia chuyến trải nghiệm thực tế giữa kì nghỉ hè", ImageUrl = "resource/images/news8.png",Content = "Hiếm khi có dịp được chứng kiến tận mắt quy trình thực hiện những sản phẩm thủ công ngoài đời thực, vì thế các bạn lớp tiếng Anh và Vi tính của trường Thăng Long đã thực sự có một trải nghiệm thú vị tại Trung tâm Giáo dục nghề nghiệp cho người khuyết tật và trẻ mồ côi (huyện Hóc Môn) vào giữa tháng 7 vừa qua. <br/> <br/> Trong dịp ghé thăm, 85 học sinh được chia thành 5 nhóm, lần lượt trải nghiệm những ngành nghề mà các bạn khuyết tật/mồ côi được đào tạo tại đây. Ở lớp may công nghiệp, các bạn được hướng dẫn đo cắt vải theo khuôn rập, tạo hình một số mẫu quần áo cơ bản, và quan sát học viên thực hiện những đường khâu tỉ mỉ để hoàn thiện một sản phẩm may mặc. Lớp vẽ tranh sơn dầu được đứng lớp bởi một thầy giáo kinh nghiệm, và thầy đã chia sẻ về chất liệu sơn dầu, cách tìm bố cục, đề tài, phác thảo và phối màu đơn giản.<br/> <br/> Một khu vườn nhỏ bên ngoài là không gian cho lớp thực hành nông nghiệp. Tại đây, các em có cơ hội quan sát kỹ thuật trồng và chăm sóc nấm, tham quan vườn hoa lan, và hăng hái phát quang cây cỏ, bụi rậm, để thông thoáng cảnh quan xung quanh khuôn viên. Ngoài ra, theo quan sát, học sinh đặc biệt yêu thích lớp hoa đất sét, nơi các em được tự tay nhào nặn bột, định hình từng cánh hoa thật khéo léo để có thể mô phỏng y hệt hoa tươi; và lớp kim hoàn, khi các em sử dụng công cụ chuyên dụng để chế tạo những món trang sức nho nhỏ dưới sự trợ giúp của các bạn học viên. Trường Phương Ninh bao gồm 1 cơ sở chính và 2 điểm lẻ nhỏ, là nơi tập học của khoảng 600 em học sinh cấp 1 và cấp 2 mỗi năm. Cơ sở chính của trường – nơi sẽ đón nhận những lớp học mới, được xây dựng từ cuối thập niên 80. Theo chia sẻ của nhiều giáo viên và học sinh, từ nhiều năm nay, cơ sở vật chất tại nhà trường đã bắt đầu xuống cấp. Các bức tường bắt đầu xuất hiện các vết nứt, lớp sơn bong tróc, cấu trúc trụ cột bê tông bị xói mòn, và khu vực sân ngoài trời phủ đầy rong rêu nên dễ gây trơn trượt nguy hiểm.Ngoài ra, trường Phương Ninh tọa lạc ngay cạnh bên khu bảo tồn thiên nhiên ngập nước chưa được khai phá nhiều; vì thế mỗi khi vào mùa mưa, học sinh còn có thể bắt gặp cá và thậm chí là đỉa, vắt xuất hiện trong sân trường. Chưa kể, mái tôn dột và máng xói mục rữa khiến lớp học bị ngập nước và hệ quả là các em từng phải nghỉ học khoảng một tháng để tránh lụt. "}
            };
        }

        private List<YKien> createDSGYList()
        {
            return new List<YKien>
            {
                new YKien(){userName="user10", date="04/11/2003",message="hello"},
                new YKien(){userName="user2", date="04/11/2003",message="hello"}
            };
        }

       

        private List<User> createUList()
        {
            return new List<User>
            {
                new User(){userName="user10",password="user10", reEnterPassword="user10",address="HN", email="Aaaa",phoneNumber="08439034803"},
                new User(){userName="user2",password="user2", reEnterPassword="user2",address="HN", email="A@aaa",phoneNumber="08439774803"},
                new User(){userName="admin",password="admin", reEnterPassword="admin",address="HN", email="Aaaa",phoneNumber="08439034803"}
            };
        }

        private List<CTTintuc> createDSCTTT()
        {
            return new List<CTTintuc>
            {
                new CTTintuc{ID=1, BannerUrl="resource/images/banner-news1.png", Title="Phòng vi tính “vượt sông” đến với trường Tiểu học Phương Phú 2", ImageUrl="resource/images/news1.png", Content="Điểm Bình Hòa B thuộc trường Tiểu học Phương Phú 2 nằm sâu trong vùng nông thôn xã Phương Phú, huyện Phụng Hiệp. Có hai phương tiện chính để học sinh đến trường: một là đi trên con đường trải nhựa với chiều rộng chỉ vừa một chiếc xe máy, hoặc di chuyển bằng ghe.<br/> <br/> Nằm tại vị trí đặc thù như vậy, có được cơ sở vật chất đầy đủ đòi hỏi rất nhiều nỗ lực từ phía nhà trường. Vì thế, 16 bộ máy vi tính mới tinh, được tài trợ bởi công ty Positive Thinking Company APAC, như một ước mơ đã trở thành sự thật đối với giáo viên và học sinh tại trường vào ngày 8/9 vừa qua. <br/> <br/> Trước đây, điểm Bình Hòa chưa được trang bị phòng vi tính. Mỗi khi đến tiết thực hành tin học, học sinh phải di chuyển trên quãng đường 5km đến cơ sở chính, và không chỉ 1 mà tận 5 – 6 em chia sẻ một chiếc máy tính với nhau. Ngoài ra, những năm gần đây, các cuộc thi trực tuyến từ Bộ Giáo dục nhận được đông đảo sự quan tâm của học sinh phổ thông. Việc thiếu thiết bị phục vụ học tập tại nhà trường đã vô tình khiến quá trình tham gia của họ sinh trở nên ít linh động hơn, khi phần lớn các em phụ thuộc vào việc mượn laptop cá nhân từ giáo viên. <br/> <br/> Hy vọng rằng, với với các máy tính được tài trợ bởi công ty Positive Thinking như bây giờ, 200 học sinh mỗi năm từ các khối lớp sẽ có cơ hội học lý thuyết lẫn thực hành tại trường, tìm hiểu và rèn luyện để củng cố và nâng cao kiến thức, và đặc biệt là có trải nghiệm học tập thuận tiện và đa dạng hơn trước.\r\n\r\nĐiểm Bình Hòa B này cũng là ngôi trường vừa được khánh thành vào tháng 3 vừa qua với 2 phòng học mới để thay thế cơ sở hạ tầng đã bị hư hại xuống cấp trước đây, cũng như để giúp gom 3 điểm lẻ của trường về chung một nơi, để các em được tận hưởng cơ sở vật chất khang trang hơn và những hỗ trợ tập trung hơn, tăng cường chất lượng học tập."},
                new CTTintuc{ID=2, BannerUrl="resource/images/banner-news2.jpg", Title="Trung thu đủ đầy, niềm vui trọn vẹn cho trẻ em Đồng Nai", ImageUrl="resource/images/news2.png", Content="Trung thu – lễ rước đèn tháng 8, có thể coi là một trong những lễ hội trong trẻo nhất của trẻ em Việt Nam. Thế nhưng không phải em bé nào cũng có điều kiện được tận hưởng những khoảnh khắc của Trung thu như xem múa lân, rước lồng đèn, ăn bánh dẻo bánh nướng. Chính vì thế, hàng năm, chương trình học bổng của saigonchildren lại luân phiên tổ chức lễ hội Trung thu cho trẻ em khó khăn tại mỗi tỉnh thành mà chương trình hoạt động. <br/> <br/> Năm nay, lễ hội Trung thu ở Đồng Nai diễn ra với sự tham gia của gần 400 trẻ em từ cấp tiểu học đến THPT. Những phần quà trao tặng đến các em cũng được đóng góp từ nhiều nhà tài trợ khác nhau, nhưng trong đó có một “nhà tài trợ” đặc biệt nhất: nhóm sinh viên và cựu sinh viên nhận học bổng của saigonchildren. <br/> <br/> Chính các em đã tự tổ chức các hoạt động gây quỹ để quyên góp được 29 triệu đồng, trao tặng 200 phần đèn học cho các em nhỏ giống như mình đã từng. Không chỉ là một phần quà, đó còn là lời gửi gắm tiếp bước từ các anh chị đi trước để các em nhỏ cố gắng vượt qua hoàn cảnh để theo đuổi tới cùng con đường tri thức."},
                new CTTintuc{ID=3, BannerUrl="resource/images/banner-news2.jpg", Title="Lần đầu đi thăm nông trại cùng các bạn nhỏ Cao Bằng", ImageUrl="resource/images/news3.png",Content="Giữa mùa hè oi ả, 24 bé nhỏ đang tham gia lớp Can thiệp sớm miễn phí của saigonchildren dành cho trẻ tự kỷ có hoàn cảnh khó khăn, cùng với người chăm sóc và các anh chị em thân thiết, đã cùng nhau hòa mình vào thiên nhiên trong chuyến đi dã ngoại vào cuối tuần qua. <br/> <br/> Năm nay, đồng hành cùng trẻ trong chuyến tham quan còn có các cô chú tình nguyện viên đến từ công ty Intel Việt Nam. Đến với nông trại, các “nông dân nhí” vô cùng phấn khởi khi lần đầu nhìn thấy và chạm vào các loài thú thân thiện được nuôi tại đây. Các bé cũng không ngại chơi với bùn đất, bắt cá bắt ốc, đến thăm vườn rau xanh mát, hay xới đất trồng cây trong những chiếc chậu nhỏ xinh. Các bé sớm trở nên khắng khít và cởi mở với các cô chú sau khi cùng trải qua các trò chơi thú vị trong cả buổi sáng hôm ấy. <br/> <br/> Gác lại giờ nghỉ trưa để nạp năng lượng, các em đều háo hức bước vào hoạt động tô tượng, nặn đất sét, và tự tay gói bánh ít để rèn luyện sự khéo léo và tính kiên nhẫn. Cuối ngày, hàng loạt tiết mục văn nghệ góp vui bởi các bé cũng được trình diễn một cách ngẫu hứng và tràn ngập tiếng cười dưới sự cổ vũ nhiệt tình từ các cô chú tài trợ. Phụ huynh bé M. chia sẻ, “Mọi năm, rất ít có cơ hội cho bé đi chơi ngoài trời với đông bạn bè như thế, và cũng như được gặp nhiều loài động vật đến vậy. Nhìn bé chơi vui thế này thì chị cũng mừng và vui lây.” <br/> <br/> Vận động ngoài trời không chỉ quan trọng với sự phát triển toàn diện của trẻ tự kỷ mà nó còn thật đáng quý, bởi lẽ vì những khó khăn về giao tiếp và hành vi, hiếm khi có dịp các em được thỏa thích nô đùa ở một không gian mới mẻ bên ngoài gia đình hay trường lớp. Trẻ em, dù là ai, cũng đều xứng đáng có được những trải nghiệm thích hợp và kỷ niệm tuổi thơ đáng nhớ."},
                new CTTintuc{ID=4,BannerUrl="resource/images/banner-news4.png", Title="Mở thêm phòng học vi tính mới cho học sinh trường Tiểu học Kinh Cùng", ImageUrl="resource/images/news4.png",Content="Trường Tiểu học Kinh Cùng (huyện Phụng Hiệp) hiện có 28 lớp học với gần 1000 học sinh, trong đó chỉ có một phòng vi tính duy nhất đã được đưa vào sử dụng nhiều năm. Đây là nơi hàng tuần, học sinh bắt đầu từ khối lớp 2 tham gia vào các buổi học Tin học thực hành. Tuy nhiên, hiện tại hơn một nửa trong số dàn máy vi tính đã bị hư hỏng ở nhiều mức độ khác nhau. <br/> <br/> Vào ngày 18/8 vừa qua, phòng máy vi tính thứ hai vừa được khánh thành tại ngôi trường này, thông qua nguồn tài trợ kinh phí từ Manulife Việt Nam, cùng với vốn đối ứng của địa phương. Với sự đầu tư cơ sở vật chất mới, hy vọng môi trường học tập của các em đã được cải thiện tốt hơn, để được đáp ứng nhu cầu học tập đầy đủ và đảm bảo tiến độ theo chương trình học phổ thông mới. <br/> <br/> Sau phần lễ, nhiều học sinh đã háo hức mong đợi được bước vào phòng máy mới, chạm tay vào màn hình và bàn phím hiện đại trong lần sử dụng đầu tiên. Trong phần trải nghiệm này, các em còn được tham gia vào trò chơi nhỏ với cô hội những được phần quà lưu niệm từ Manulife. Hai em bất kỳ trở thành một đội chơi, cùng với sự hỗ trợ từ 1 thành viên đoàn tài trợ, tô màu bức tranh theo quy định ở hình ảnh mẫu linh vật “Manubear”, và sẽ tự do hoàn thành phần còn lại theo ý thích. Các em thực sự đã có một khoảng thời gian vui vẻ khi nhìn thấy điều kỳ diệu của máy vi tính và sự sáng tạo của các em đã tạo nên tác phẩm đẹp mắt thế nào. <br/> <br/>"},
                new CTTintuc{ID=5, BannerUrl="resource/images/banner-news2.jpg",Title="Một khởi đầu tốt đẹp hơn đến với trẻ em có nhu cầu đặc biệt", ImageUrl="resource/images/news5.png", Content="Kể từ năm 2018, dự án Phục hồi chức năng dựa vào cộng đồng – thuộc chương trình Giáo dục Đặc biệt của saigonchildren, bắt đầu được triển khai thực hiện, với mục đích hỗ trợ trẻ khó khăn vận động và các vấn đề phát triển khác tiếp cận với các dịch vụ trị liệu để cải thiện kỹ năng vận động và xã hội. Dự án được thực hiện tại lớp Can thiệp sớm thuộc Mái ấm Teresa Calcutta (Quận 11), với khoảng 30 trẻ được hỗ trợ hàng năm.<br/> <br/> Những trẻ thụ hưởng từ dự án gặp các trở ngại khác nhau trong việc di chuyển và giao tiếp bằng ngôn ngữ, khiến các em không thể hòa nhập tốt vào các hoạt động thường nhất, ví dụ như đến trường hoặc giao lưu cùng bạn bè. Hơn thế, hầu hết các em đến từ những gia đình có khó khăn kinh tế, và nếu như phải nghĩ đến trường hợp đưa con đến các trung tâm hồi phục, đó sẽ là gánh nặng tài chính vô cùng lớn đối với phụ huynh.Với sự hỗ trợ của saigonchildren – cung cấp kinh phí duy trì các hợp phần về vật lý trị liệu, âm ngữ trị liệu, và giáo dục đặc biệt, nhiều trẻ đã thực hiện các hoạt động di chuyển trong sinh hoạt hằng ngày hoặc leo cầu thang dễ dàng hơn; cũng như cho thấy nhiều cải thiện đáng nể trong kỹ năng ngôn ngữ, nhận thức, và sức khỏe tâm thần. Một vài em thậm chí đã có đủ kỹ năng để tham gia giáo dục hòa nhập tại trường công lập.<br/> <br/> Đến nay, đã có khoảng 150 trẻ giảm chức năng vận động và phát triển được hưởng lợi từ dự án này, trong số đó có Minh Quang và Khải Hùng. Sau khi tham gia can thiệp vật lý trị liệu và âm ngữ trị liệu thích hợp và kịp thời, giờ đây, hai bạn nhỏ đã “tốt nghiệp”, khi có thể tự đi đứng thăng bằng, phát âm rành mạch, chuẩn xác, và chủ động nhiều hơn trong giao tiếp. Bên cạnh việc sử dụng nguồn lực từ giáo viên và nhà trị liệu giàu kinh nghiệm, dự án ý nghĩa nàynày cũng đã đề cao nhận thức, năng lực và tự tin, đến phụ huynh và người giám hộ trẻ, để cho phép họ cung cấp sự hỗ trợ lớn hơn cho con cái của mình tại nhà.</br> <br/> Từ năm 2023, saigonchildren đón nhận Edrington là nhà đồng hành kế tiếp triển khai dự án Phục hồi chức năng dựa vào cộng đồng, với mục tiêu tiếp tục giúp đỡ trẻ em có nhu cầu đặc biệt có đủ kỹ năng để tham gia giáo dục hòa nhập, và có được một khởi đầu tốt đẹp hơn trong cuộc sống."},
                new CTTintuc{ID=6,BannerUrl="resource/images/banner-news6.png",Title="Học sinh Thăng Long thể hiện khả năng ngoại ngữ ngoài môi trường lớp học",ImageUrl="resource/images/news6.jpg",Content="Cuối tuần qua chắc hẳn là một dịp bận rộn nhưng cũng đầy hào hứng đối với học sinh lớp ngoại ngữ tại Trường dạy tiếng Anh và dạy Nghề Thăng Long, khi các em có mặt tại Nhà Thiếu nhi TP.HCM tham gia vào Ngày hội Tiếng Anh được tổ chức thường niên của trường. Sự kiện còn chào đón đội ngũ nhân viên Hanwha Life Việt Nam đến chung vui và hỗ trợ các em nhiệt tình trong cả buổi sáng.<br/> <br/> Xuyên suốt ngày Hội, các học viên chia thành 5 đội, tranh tài vượt qua các trạm thử thách. Ở nhiệm vụ đầu tiên, mỗi bạn nhảy bao bố vượt chướng ngại vật đến vạch đích, mang về một tấm thẻ có chứa từ vựng, và ghép thành cụm từ tiếng Anh có ý nghĩa liên quan đến chủ đề ngày hội.<br/> <br/> Trò chơi tiếp theo đòi hỏi kỹ năng khéo léo và phán đoán, khi từng thành viên đội sẽ đeo bịt mắt, đi đến nơi có tấm tranh vẽ và dịch nghĩa chúng sang tiếng Anh. Bước qua thử thách truyền tin, cả đội sẽ tham gia chơi cùng một lượt. Trong lúc nhạc bật thật to, người đứng đầu hàng đọc lại câu nói về quyền trẻ em mà đã bốc thăm trước đó cho bạn đứng tiếp theo, và cứ thế truyền đạt thông tin đến bạn cuối cùng trong nhóm, và viết lại những gì nghe được trên bảng.<br/> <br/> Cuối cùng, hoạt động mong chờ nhất trong ngày hội chính là phần thi diễn kịch với nhiều bất ngờ. Thời gian vô cùng ngắn khi chưa đến một giờ đồng hồ kể từ lúc nhận nhiệm vụ, nhưng tất cả thành viên đều làm việc nhóm hiệu quả dưới sự dẫn dắt của đội trưởng. Các em đã tự thực hiện kịch bản, phân vai và câu thoại, mạnh dạn trình diễn phần giải quyết tình huống bằng tiếng Anh một cách thuyết phục."},
                new CTTintuc{ID=7,BannerUrl = "resource/images/banner-news7.png", Title = "2 ngày 1 đêm tràn ngập thanh âm tuổi trẻ của các bạn học sinh",ImageUrl = "resource/images/news7.png",Content="Cuối tháng 7 này, Trại hè Sinh viên 2023 vừa được diễn ra tại Đồng Nai dành cho sinh viên đang và đã nằm trong chương trình học bổng của saigonchildren ở cấp bậc đại học. Như mọi năm, Trại hè như một hoạt động ngoại khóa để các bạn có cơ hội tham gia vui chơi, hình thành các kỹ năng và mối quan hệ bạn bè mới; cũng như để gạt đi nỗi âu lo trong cuộc sống và tìm thấy nơi thể hiện sự nhiệt huyết tuổi trẻ vốn có của mình. <br/> <br/> Chủ đề trại năm nay mang tên “Happy Bridges” – trở thành chiếc cầu nối giữa các cá nhân xa lạ lại gần nhau hơn. Vì thế trong lần tổ chức này, các trại sinh đã cùng lăn xả hết mình với những thử thách được đề ra, với mục đích phát huy tinh thần đoàn kết đồng đội và văn hóa tập thể.<br/> <br/> Cuộc chơi khởi động bằng hoạt động dựng và trang trí lều trại bằng bóng bay, sáng tạo bảng tên nhóm thật phong cách và trình bày ý nghĩa của chúng trước Ban giám khảo để nhận các số điểm đầu tiên. Sự háo hức được tiếp tục khi tiến tới Lễ khai mạc và tiến hành các nghi thức đặc trưng, bao gồm vẽ mặt màu và nhảy theo bài hát chủ đề trại."},
                new CTTintuc{ID=8,BannerUrl = "resource/images/banner-news8.png", Title = "Tham gia chuyến trải nghiệm thực tế giữa kì nghỉ hè", ImageUrl = "resource/images/news8.png",Content = "Hiếm khi có dịp được chứng kiến tận mắt quy trình thực hiện những sản phẩm thủ công ngoài đời thực, vì thế các bạn lớp tiếng Anh và Vi tính của trường Thăng Long đã thực sự có một trải nghiệm thú vị tại Trung tâm Giáo dục nghề nghiệp cho người khuyết tật và trẻ mồ côi (huyện Hóc Môn) vào giữa tháng 7 vừa qua. <br/> <br/> Trong dịp ghé thăm, 85 học sinh được chia thành 5 nhóm, lần lượt trải nghiệm những ngành nghề mà các bạn khuyết tật/mồ côi được đào tạo tại đây. Ở lớp may công nghiệp, các bạn được hướng dẫn đo cắt vải theo khuôn rập, tạo hình một số mẫu quần áo cơ bản, và quan sát học viên thực hiện những đường khâu tỉ mỉ để hoàn thiện một sản phẩm may mặc. Lớp vẽ tranh sơn dầu được đứng lớp bởi một thầy giáo kinh nghiệm, và thầy đã chia sẻ về chất liệu sơn dầu, cách tìm bố cục, đề tài, phác thảo và phối màu đơn giản.<br/> <br/> Một khu vườn nhỏ bên ngoài là không gian cho lớp thực hành nông nghiệp. Tại đây, các em có cơ hội quan sát kỹ thuật trồng và chăm sóc nấm, tham quan vườn hoa lan, và hăng hái phát quang cây cỏ, bụi rậm, để thông thoáng cảnh quan xung quanh khuôn viên. Ngoài ra, theo quan sát, học sinh đặc biệt yêu thích lớp hoa đất sét, nơi các em được tự tay nhào nặn bột, định hình từng cánh hoa thật khéo léo để có thể mô phỏng y hệt hoa tươi; và lớp kim hoàn, khi các em sử dụng công cụ chuyên dụng để chế tạo những món trang sức nho nhỏ dưới sự trợ giúp của các bạn học viên. Trường Phương Ninh bao gồm 1 cơ sở chính và 2 điểm lẻ nhỏ, là nơi tập học của khoảng 600 em học sinh cấp 1 và cấp 2 mỗi năm. Cơ sở chính của trường – nơi sẽ đón nhận những lớp học mới, được xây dựng từ cuối thập niên 80. Theo chia sẻ của nhiều giáo viên và học sinh, từ nhiều năm nay, cơ sở vật chất tại nhà trường đã bắt đầu xuống cấp. Các bức tường bắt đầu xuất hiện các vết nứt, lớp sơn bong tróc, cấu trúc trụ cột bê tông bị xói mòn, và khu vực sân ngoài trời phủ đầy rong rêu nên dễ gây trơn trượt nguy hiểm.Ngoài ra, trường Phương Ninh tọa lạc ngay cạnh bên khu bảo tồn thiên nhiên ngập nước chưa được khai phá nhiều; vì thế mỗi khi vào mùa mưa, học sinh còn có thể bắt gặp cá và thậm chí là đỉa, vắt xuất hiện trong sân trường. Chưa kể, mái tôn dột và máng xói mục rữa khiến lớp học bị ngập nước và hệ quả là các em từng phải nghỉ học khoảng một tháng để tránh lụt. "},
                new CTTintuc{ID=9,BannerUrl = "resource/images/banner-news9.png", Title = "Học sinh Phương Ninh háo hức mong chờ phòng học mới", ImageUrl = "resource/images/news9.png",Content = "Trường Tiểu học và THCS Phương Ninh (xã Phương Bình, huyện Phụng Hiệp, tỉnh Hậu Giang) được các nhân viên chương trình Xây trường và Môi trường học đường khảo sát trong chuyến công tác vào tháng 8.2022 và lần đầu đề cập đến trong đêm dạ tiệc gây quỹ Saigon Summer Ball lần thứ 13 của saigonchildren. Sau hơn 8 tháng kể từ thời điểm đó, ngôi trường ở vùng sâu xa này sắp sửa “khoác” lên mình một “chiếc áo mới”.<br/> <br/> Vào ngày 08/06 vừa qua, lễ khởi công xây dựng phòng học và sân trường mới tại ngôi trường này đã được diễn ra. Bên cạnh nguồn vốn đối ứng từ phía chính quyền điạ phương, công trình này được thi công còn nhờ vào sự đóng góp của Corrina Lim và bạn bè, những người ủng hộ trong sự kiện Saigon Summer Ball 2022, nhân viên từ doanh nghiệp Capital Group cùng rất nhiều nhà hảo tâm khác."},
                new CTTintuc{ID=10,BannerUrl = "resource/images/banner-news10.png", Title = "Học đi đôi với hành cho các học viên nghề sửa chữa ô tô", ImageUrl = "resource/images/news10.jpg",Content = "Từ tháng 07.2022 – 07.2023, 25 thanh thiếu niên đã xuất sắc nhận được các suất học bổng huấn luyện kỹ năng nghề với sự tài trợ của Motul Việt Nam. Đây đều là những em có xuất phát điểm khó khăn đang theo học chuyên ngành cơ khí và sửa chữa ô tô được chiêu sinh từ các trường cao đẳng, trung cấp đang thiếu điều kiện để theo đuổi ước mơ học tập của mình.<br/> <br/> Mỗi gói học bổng sẽ chi trả toàn bộ học phí, dụng cụ học tập, các buổi tham vấn tâm lý xã hội khi cần thiết, cũng như các hoạt động phát triển kỹ năng mềm. Mỗi em học viên trong chương trình sẽ nhận được hỗ trợ 1-1 và tư vấn các khóa đào tạo nghề phù hợp và định hướng công việc sau này. <br/> <br/> Vào cuối năm ngoái, các em học viên trong chương trình đã có buổi gặp gỡ đầu tiên với ban quản lý của Motul Việt Nam và các chủ ga-ra tại trường Thăng Long. Đây là dịp để các em tìm hiểu về trao đổi trực tiếp những thắc mắc liên quan đến ngành học và cơ hội việc làm sau tốt nghiệp nhằm giúp các em trở nên tự tin hơn trước khi bước chân vào nghề. <br/> <br/> Những câu hỏi của các em chủ yếu xoay quanh nội chủ đề như thời gian làm việc, những yêu cầu cần đáp ứng trong công việc, chế độ lương thưởng, các kiến thức được các ga-ra đào tạo và các kỹ năng cần tự rèn luyện để nâng cao tay nghề, cơ hội nghề nghiệp trong tương lai,…. Từ những thắc mắc trên, các đại diện ga-ra đã có những phản hồi vô cùng cụ thể nhằm giúp các em có thông tin rõ ràng nhất. Anh Trương Minh Định – chủ ga-ra ô tô Nam Sài Gòn đã nhấn mạnh rằng, “Điều đầu tiên khi bước vào nghề là phải trung thực, siêng năng và chịu khó học hỏi từ những người đi trước. Chia sẻ này nhắc nhở các bạn sinh viên rằng để phát triển bản thân thì điều quan trọng nhất là phải “học”.”"},
                new CTTintuc{ID=11,BannerUrl = "resource/images/banner-news11.png", Title = "Ngày hội dinh dưỡng cùng trẻ em Tiểu học Trà Vinh", ImageUrl = "resource/images/news11.jpg",Content = "Vào ngày 23 tháng Tư 2023, tại trường Tiểu học Hiếu Trung B (huyện Tiểu Cần, tỉnh Trà Vinh) đã diễn ra ngày hội dinh dưỡng với chủ đề “Bữa ăn Thông thái – Ươm mầm Tương lai” dành cho 405 em đang học tập tại ngôi trường này. Đây là sự kiện nằm trong hợp phần dinh dưỡng cho hơn 1.000 trẻ em có hoàn cảnh khó khăn tại tỉnh Trà Vinh, thuộc dự án “Cùng nhau hành động – Hỗ trợ nỗ lực phục hồi hậu COVID-19” mà Saigon Children’s Charity thực hiện với sự hỗ trợ của Prudential Việt Nam tại hai tỉnh Trà Vinh và Bình Thuận. <br/> <br/> Vào hôm ấy, các em đã được tìm hiểu về tháp dinh dưỡng cũng như giá trị dinh dưỡng của các món ăn thông qua trò chơi “Chiếc hộp bí mật”. Không những thế, các em còn được hướng dẫn về cách “tô màu cho bữa ăn” để học về đa dạng chất dinh dưỡng thông qua màu sắc các món trong bữa ăn, cũng như quy tắc phân bổ để có một bữa ăn cân bằng các nhóm chất. Sự kiện còn có sự tham gia của hơn 100 phụ huynh trong hoạt động hội thảo cùng chuyên gia, qua đó phụ huynh được chia sẻ các quy tắc cơ bản để xây dựng bữa ăn lành mạnh, dinh dưỡng cho trẻ. <br/> <br/> Trong suốt 55 ngày, từ tháng Ba cho đến hết năm học 2022 – 2023, 64.900 bữa phụ đã được hỗ trợ cho 1.180 học sinh mẫu giáo và tiểu học tại huyện Tiểu Cần, bao gồm thực hiện tại 4 trường, trong đó có hai trường mẫu giáo (Hiếu Tử, Hùng Hoà) và hai trường tiểu học (Hiếu Tử C, Hiếu Trung B). Vào mỗi buổi sáng, những chuyến xe chở đầy thức ăn sẽ đáp tại sân trường, các thầy cô phụ trách nhận nhiệm vụ phân loại và sắp xếp ngay ngắn để đảm bảo có đủ khẩu phần theo từng lớp học, từng loại chay và mặn khác nhau. Những lớp nhỏ sẽ được thầy cô đưa suất ăn đến tận lớp học; trong khi các em lớn hơn sẽ cử đại diện đến nơi tập trung và mang chúng về lớp cho các bạn vào lúc 9g sáng."},
                new CTTintuc{ID=12,BannerUrl = "resource/images/banner-news12.png", Title = "Khởi công dự án xây dựng trường học Hiếu Tử C tại Trà Vinh", ImageUrl = "resource/images/news12.jpg",Content = "Vào ngày 19 tháng 4 năm 2023, lễ khởi công dự án xây trường tiểu học Hiếu Tử C đã diễn ra tại xã Hiếu Tử, huyện Tiểu Cần, tỉnh Trà Vinh. Hứa hẹn mang đến môi trường học tập tốt và an toàn hơn cho gần 100 em nhỏ, dự án này nằm trong chương trình “Xây dựng Trường học và Cải thiện Môi trường Học đường” của Saigon Children’s Charity, với nguồn tài chính từ công ty BASF và các đối tác (MKVN, Nippon Paint, Phuong Nam Panel, Sam Chem Sphere, Tam Trần, Viet Duc JSC), các nhà tài trợ khác, cùng vốn đối ứng từ chính quyền địa phương. <br/> <br/> Trường Hiếu Tử C thuộc vùng có hoàn cảnh kinh tế – xã hội đặc biệt khó khăn, nằm ở vùng có dân cư thưa thớt, nghèo nàn. Trường có một điểm chính và ba điểm phụ. Dự án này tập trung cải thiện một trong ba điểm phụ, cụ thể là điểm trường Ô Trao. <br/> <br/>  Dự án sẽ xây hai phòng học mới và làm lại 200m2 sân chơi để các em học sinh không những có thêm không gian mà còn được học tập trong một môi trường khang trang, và quan trọng là an toàn hơn. Dự kiến ngôi trường mới sẽ sẵn sàng để đón các em học sinh vào tháng 10 năm 2023. <br/> <br/> Điểm trường Hiếu Tử C tại ấp Ô Trao hiện có bốn phòng học, là nơi học tập của 162 em học sinh tuổi từ 6 đến 11, trong đó 159 em là người dân tộc thiểu số. Mỗi lớp có thể có tới 40 học sinh, gây ảnh hưởng đến khả năng tập trung chú ý của các em cũng như mức độ quan tâm của giáo viên tới từng học sinh. Hơn thế nữa, điểm trường ban đầu chỉ được xây tạm và hiện ở trong tình trạng xuống cấp nghiêm trọng. Phòng học rất nóng vào mùa khô và rất ồn vào mùa mưa lại càng khiến cho việc dạy và học trở nên khó khăn hơn."}
            };
        }

        private List<Tintuc> createDSTT()
        {
            return new List<Tintuc>
               {
                   new Tintuc{ID=1,Title="Phòng vi tính “vượt sông” đến với trường Tiểu học Phương Phú 2", ImageUrl="resource/images/news1.png"},
                   new Tintuc{ID=2,Title="Trung thu đủ đầy, niềm vui trọn vẹn cho trẻ em Đồng Nai", ImageUrl="resource/images/news2.png"},
                   new Tintuc{ID=3,Title="Lần đầu đi thăm nông trại cùng các bạn nhỏ Cao Bằng", ImageUrl="resource/images/news3.png"},
                   new Tintuc{ID=4,Title="Mở thêm phòng học vi tính mới cho học sinh trường Tiểu học Kinh Cùng", ImageUrl="resource/images/news4.png"},
                   new Tintuc{ID=5,Title="Một khởi đầu tốt đẹp hơn đến với trẻ em có nhu cầu đặc biệt", ImageUrl="resource/images/news5.png"},
                   new Tintuc{ID=6,Title="Học sinh Thăng Long thể hiện khả năng ngoại ngữ ngoài môi trường lớp học", ImageUrl="resource/images/news6.jpg"},
                   new Tintuc{ID=7,Title="2 ngày 1 đêm tràn ngập thanh âm tuổi trẻ của các bạn học sinh", ImageUrl="resource/images/news7.png"},
                   new Tintuc{ID=8,Title="Tham gia chuyến trải nghiệm thực tế giữa kì nghỉ hè", ImageUrl="resource/images/news8.png"},
                   new Tintuc{ID=9,Title="Học sinh Phương Ninh háo hức mong chờ phòng học mới", ImageUrl="resource/images/news9.png"},
                   new Tintuc{ID=10,Title="Học đi đôi với hành cho các học viên nghề sửa chữa ô tô", ImageUrl="resource/images/news10.jpg"},
                   new Tintuc{ID=11,Title=" Ngày hội dinh dưỡng cùng trẻ em Tiểu học Trà Vinh", ImageUrl="resource/images/news11.jpg"},
                   new Tintuc{ID=12,Title="Khởi công dự án xây dựng trường học Hiếu Tử C tại Trà Vinh", ImageUrl="resource/images/news12.jpg"}

               };
        }
        protected void Session_Start(object sender, EventArgs e)
        {
            //Session.Timeout = 1;
            Session["dem"] = 0;
            Session[USERNAME] = "guest";
            Session[PASSWORD] = "guest";
            Session[State] = "null";
        }

        protected void Application_BeginRequest(object sender, EventArgs e)
        {

        }

        protected void Application_AuthenticateRequest(object sender, EventArgs e)
        {

        }

        protected void Application_Error(object sender, EventArgs e)
        {

        }

        protected void Session_End(object sender, EventArgs e)
        {

        }

        protected void Application_End(object sender, EventArgs e)
        {

        }
    }
}